---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-20.04-default
    image: ubuntu:20.04
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
