---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check terraform version
    command: ~/bin/terraform version
    register: terraform_version_result
    changed_when: false
  - name: Terraform is installed
    assert:
      that: terraform_version_result.stdout_lines[0] is match("Terraform")
