---
name: Run tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "26 5 * * 2"

jobs:
  molecule:
    name: Molecule test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro:
          - ubuntu:24.04
          - ubuntu:22.04
        ansible:
          - ansible
          - ansible==11.*

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: python3 -m pip install "${{ matrix.ansible }}" -Ur requirements-molecule.txt

      - name: Run Molecule tests
        run: molecule test --all
        env:
          PY_COLORS: '1'  # for molecule
          ANSIBLE_FORCE_COLOR: 'True'
          MOLECULE_DISTRO: '${{ matrix.distro }}'
