---
name: Run tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "26 5 * * 2"

defaults:                             # TODO: Remove after the fix is released, see
  run:                                #       https://github.com/ansible-community/molecule/pull/3409
    working-directory: 'giner.tfenv'  #

jobs:
  molecule:
    name: Molecule test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu:22.04
          - ubuntu:20.04
        ansible:
          - ansible
          - ansible==2.9.*
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:                   # TODO: Remove after the fix is released, see
          path: 'giner.tfenv'   #       https://github.com/ansible-community/molecule/pull/3409
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install test dependencies
        run: python3 -m pip install "${{ matrix.ansible }}" -Ur requirements-molecule.txt
      - name: Install ansible collections required for Ansible 2.9
        if: matrix.ansible == 'ansible==2.9.*'
        run: ansible-galaxy collection install community.docker
      - name: Run Molecule tests
        run: molecule test --all
        env:
          PY_COLORS: '1'  # for molecule
          ANSIBLE_FORCE_COLOR: 'True'
          MOLECULE_DISTRO: '${{ matrix.distro }}'
